In [1]:
import pandas as pd
import requests as rq
import lxml as xl
import pytrends
from pytrends.request import TrendReq
pytrends = TrendReq()

In [2]:
topic_ls = ["easter", "bunny", "murders"]

In [3]:
my_req = TrendReq(hl='en-US', tz=360)
my_req.build_payload(topic_ls)
my_req.interest_over_time()

            easter  bunny  murders  isPartial
date
2015-04-19       4      4        1      False
2015-04-26       4      4        1      False
2015-05-03       3      4        1      False
2015-05-10       3      4        1      False
2015-05-17       3      4        2      False
...            ...    ...      ...        ...
2020-03-08      14      7        2      False
2020-03-15      12      6        2      False
2020-03-22      21      8        2      False
2020-03-29      29     11        2      False
2020-04-05      77     15        2      False

[260 rows x 4 columns]