In [1]:
import pandas as pd
import requests as rq
import lxml as xl
import pytrends
from pytrends.request import TrendReq
pytrends = TrendReq()

In [6]:
topic_ls = ["guns", "germs", "recreation"]
gun_ls = ["ammunition", "gun stores", "ar-15"]
germs_ls = ["hand sanitizer", "bleach", "toilet paper"]
tv_ls = ["netflix", "weed", "beer"]

In [6]:
my_req = TrendReq(hl='en-US', tz=360)
my_req.build_payload(topic_ls, timeframe = 'today 3-m')
df_2019 = my_req.interest_over_time()
df_2019.head()

            guns  germs  recreation  isPartial
date
2020-01-13    50      3          20      False
2020-01-14    53      3          17      False
2020-01-15    53      4          16      False
2020-01-16    59      3          19      False
2020-01-17    59      3          17      False

In [23]:
#df_2019 = df_2019.drop("isPartial", axis =1)
df_2020 = df_2019
df_2020.to_csv('goog_csvs/topics_2020.csv')

            guns  germs  recreation
date
2020-01-13    50      3          20
2020-01-14    53      3          17
2020-01-15    53      4          16
2020-01-16    59      3          19
2020-01-17    59      3          17

In [21]:
my_req = TrendReq(hl='en-US', tz=360)
my_req.build_payload(gun_ls, timeframe = 'today 3-m')
df_gun_2020 = my_req.interest_over_time()
df_gun_2020 = df_gun_2020.drop("isPartial", axis =1)
df_gun_2020.head()

            ammunition  gun stores  ar-15
date
2020-01-16          22           8     15
2020-01-17          20          12     11
2020-01-18          22          17     11
2020-01-19          23          10     17
2020-01-20          24          10     13

In [23]:
df_gun_2020.to_csv('goog_csvs/guns_2020.csv')

In [3]:
my_req = TrendReq(hl='en-US', tz=360)
my_req.build_payload(germs_ls, timeframe = 'today 3-m')
df_germ_2020 = my_req.interest_over_time()
df_germ_2020.head()

            hand sanitizer  bleach  toilet paper  isPartial
date
2020-01-16               1       6             2      False
2020-01-17               1       7             2      False
2020-01-18               0       8             2      False
2020-01-19               1       8             2      False
2020-01-20               0       7             2      False

In [4]:
df_germ_2020 = df_germ_2020.drop("isPartial", axis = 1)
df_germ_2020.to_csv("goog_csvs/germs_2020.csv")

In [7]:
my_req = TrendReq(hl='en-US', tz=360)
my_req.build_payload(tv_ls, timeframe = 'today 3-m')
df_tv_2020 = my_req.interest_over_time()
df_tv_2020.head()

            netflix  weed  beer  isPartial
date
2020-01-16       40     5     7      False
2020-01-17       44     5     7      False
2020-01-18       54     5     9      False
2020-01-19       57     5     8      False
2020-01-20       45     5     6      False

In [8]:
df_tv_2020.drop("isPartial", axis = 1)
df_tv_2020.to_csv("goog_csvs/rec_2020.csv")